name: Deploy or Delete CloudFormation Stack

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose whether to deploy or delete the stack"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - delete

jobs:
  manage-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy stack
        if: github.event.inputs.action == 'deploy'
        run: |
          STACK_NAME=demo-ec2-stack
          TEMPLATE_FILE=templates/main.yaml
          echo "Deploying stack..."
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file $TEMPLATE_FILE \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ap-south-1 \
            --parameter-overrides KeyPairName=AWS_CF

      - name: Delete stack
        if: github.event.inputs.action == 'delete'
        run: |
          STACK_NAME=demo-ec2-stack
          echo "Deleting stack..."
          aws cloudformation delete-stack \
            --stack-name $STACK_NAME \
            --region ap-south-1
          echo "Waiting for deletion to complete..."
          aws cloudformation wait stack-delete-complete \
            --stack-name $STACK_NAME \
            --region ap-south-1
          echo "Stack deleted successfully."
